run:
  deadline: 5m
  tests: true
  skip-dirs:
    - vendor

linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - revive
    - bodyclose
    - gocyclo

linters-settings:
  gocyclo:
    min-complexity: 15
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  misspell:
    locale: US

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - gosec 