# Golangci linter configuration
# See: https://golangci-lint.run/usage/configuration/

linters-settings:
  gocyclo:
    min-complexity: 15
  govet:
    check-shadowing: true
  revive:
    confidence: 0.0
  misspell:
    locale: US
    
run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor

linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - revive
    - bodyclose
    - gocyclo

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - gosec
    - path: internal/slack/client.go
      linters:
        - gocyclo
    - path: internal/bridge/llm_mcp_bridge.go
      linters:
        - unused
    # Temporarily exclude some files from complex checks
    - path: internal/slack/client.go
      linters:
        - gocyclo
      text: "cyclomatic complexity .* of func `main` is high"
    - path: internal/bridge/llm_mcp_bridge.go
      linters:
        - unused
      text: "func .* is unused" 