# GoReleaser configuration
before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/slack-mcp-client/main.go
    binary: "{{ .ProjectName }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    ldflags:
      - -s -w -X main.Version={{.Version}}

archives:
  - format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

checksum:
  name_template: "checksums.txt"

snapshot:
  # renamed in v2.2: old `name_template` is deprecated
  version_template: "next"  

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - Merge pull request
      - Merge branch

release:
  github:
    # split "owner/name" from the built-in GITHUB_REPOSITORY
    owner: "{{ (split .Env.GITHUB_REPOSITORY \"/\").0 }}"
    name:  "{{ (split .Env.GITHUB_REPOSITORY \"/\").1 }}"
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"

